### PR TITLE
Update xerces, gwt and guava dependencies

### PR DESCRIPTION
**Pull request by pablojan**
This PR fixes gwt building issues. It also update base gwt and guava deps.

### CODE REVIEW

**Comment by pablojan** [comment]
Not sure If you was expecting me to do the merge, I don't have permissions
;)

2016-10-23 19:10 GMT+02:00 Yuri Z. <notifications@github.com>:

**Comment by wisebaldone** [comment]
hmm seems compiling gwt should be added to the ci chain

**Comment by wisebaldone** [comment]
LGTM by inspection, we be pushed on friday/saturday if yuri doesnt get too it first.

Thankyou for the contribution.

**Comment by wisebaldone** [comment]
Haha, seems inbetween this passing that guava became a full release aswell.

**Pull request merged**
