### PR TITLE
Make log-in page more friendly.

### PR DESCRIPTION
**Pull request by PeterWarrington**
Make login page more user friendly, as well as modernising the code and cleaning it up. Attached are Desktop and Mobile screenshots.

976cacf0-cd5a-4b66-9b54-1530268ca444__screencapture-192-168-0-11-9898-auth-signin-1501004757144 
b89c618c-d21a-45ab-8797-966037043159__screencapture-192-168-0-11-9898-auth-signin-1501004798625

### CODE REVIEW

**Comment by zmyaro** [comment]
I like your stated goals, but I am not sure how well the changes accomplish them.

> it drew too much attention to the top bar when we want most of the attention going to the login box.

The layout in the screenshots has a tall top bar with a lot of empty space and a login box that will almost always be pushed “below the fold”.  That is not too much of a problem since you have a “Sign in” FAB, but I am not sure whether it matches your stated intent.

More generally, I am concern that this design does not seem to have a cohesive design language, but if your goal is just an improved layout, then that can be addressed later.

**Comment by PeterWarrington** [comment]
@zmyaro In your opinion, would it be an improvement to include the Username and Password boxes within the header as well as on mobile making the sign in box a pop-up/dialog when you press the "Sign in" FAB?

_Sent from my Motorola XT1524 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by zmyaro** [comment]
I am saying if you want the sign in box to get people's attention, move it above the fold.  In the header might work OK on desktop, but I am not sure how it would look on mobile.

**Comment by PeterWarrington** [comment]
@zmyaro Sorry, I meant that if you're on mobile it won't display the boxes in the header and would instead display a FAB in the header which when pressed would display a dialog/pop-up in the center of the screen allowing the user to sign in.

_Sent from my Motorola XT1524 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by zmyaro** [comment]
That is not awful, but I am still concerned that it hides the ability to sign up for an account.  Give me a minute to mock up an idea.

**Comment by zmyaro** [comment]
What about something like this that features both links?  As a possible bonus, clicking “Sign in” could slide out the sign in form into the header.

wiab_header_mock

**Comment by PeterWarrington** [comment]
@zmyaro That is a great idea! When I get back to my computer, I will start work on it! Any other suggestions? Thanks!

_Sent from my Motorola XT1524 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by PeterWarrington** [comment]
Sorry! I had almost finished with my code and then accidentally deleted it all... This is going to take a while and will now probally go on too tomorow...

**Comment by PeterWarrington** [comment]
On holiday at moment, can't work on it for two weeks. Sorry!

_Sent from my Motorola XT1524 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Pull request closed without merging**
