### PR TITLE
WAVE-439 - Changes source compatibility to Java1.8 and fixes weird is…

### PR DESCRIPTION
**Pull request by vega113**
…sues with code that 1.8 was not backward compatible.

Some of the issues were resolved by updating to newer Java1.8 JDK version.

### CODE REVIEW

**Comment by vega113** [comment]
@wisebaldone Can you please review the PR?

**Comment by wisebaldone** [comment]
Im getting the run task failing, can you confirm? (dont think its java8 related but gwt related)

Theres also two warnings when compiling with java 8 

- src/main/java/org/waveprotocol/wave/client/doodad/selection/SelectionAnnotationHandler.java:579: warning: '_' used as an identifier 
- src/main/java/org/waveprotocol/wave/client/wavepanel/render/LiveConversationViewRenderer.java:305: warning: '_' used as an identifier

**Comment by wisebaldone** [comment]
turns out was a local linux issue, you have my +1 if you can resolve those warnings.

**Comment by vega113** [comment]
./gradlew distZip worked fine on the PR branch.
I think that config/wave.conf is a template and the actual version is taken from the gradle.build file.

**Pull request merged**
