### PR TITLE
Feature/gradle

### PR DESCRIPTION
**Pull request by wisebaldone**
Rework of the build system to use gradle instead of Ant.

see the readme on how to build the project and on how to make dist zip's.

### CODE REVIEW

**Comment by vega113** [comment]
Sorry it took so long, I looking at your changes now.

**Comment by wisebaldone** [comment]
issues with commands:

* rat: it still produces a report for me in the reports folder but doesn’t terminate the task, its been a bit strange not sure the issue.
* gwtDev: im trying to push along a patch in the gwt community that will update gwt's  jetty version to 9 instead of 8 which should solve the conflict issue.
* extractApi: Im gonna assume this is a Windows related issue since a fresh linux vm works fine with it.


Ill update the readme as requested and let you know when ive found the issue of the unable to extract.

**Comment by wisebaldone** [comment]
seems it could be a permissions issue, would you mind running with --info and posting the end of the trace

**Comment by wisebaldone** [comment]
Changes have been made.

**Comment by vega113** [comment]
Regarding wave/wave/dist/run-data-migration.sh
Can we take the version number directly from build.gradle? Is there any other use of wave.conf?

**Comment by wisebaldone** [comment]
Gradle could compile the scripts instead of them searching for a file to dynamically find the value. The current method was to replace how the ant build did it with the build.info file in the dist.

**Comment by vega113** [comment]
The dist files - on mac they were created in wave/build/distributions/
instead of wave/build/dist

**Comment by vega113** [comment]
I can't find the tasks to create the source archives.

**Comment by wisebaldone** [comment]
whats the issue with the dist files on mac?

**Comment by vega113** [comment]
The task prints info with incorrect location

**Comment by wisebaldone** [comment]
do you want the jar task to create the sourceJar's

**Comment by vega113** [comment]
They should be created in similar way like in the ant task.

**Comment by wisebaldone** [comment]
added missing task to create each subprojects source jar.

**Comment by wisebaldone** [comment]
added missing task to package up the entire source.

**Comment by wisebaldone** [comment]
Done

**Comment by wisebaldone** [comment]
In regards to all issues with gwt classpath this patch https://gwt-review.googlesource.com/#/c/7857/ will solve the temporary issues but in the long term we should seperate the gwt client from the server backend.

**Comment by wisebaldone** [comment]
They have been moved to the dist folder which puts them in the distribution binary and they work which is why i removed the note on the readme. They were disabled for a short time as I thought it was gonna be a large amount of work for the scripts to work but was fairly easy.

Is the docs folder used for anything and are there any more issues?

**Comment by vega113** [comment]
The docs folder used to include the whitepapers.

**Comment by wisebaldone** [comment]
well ill leave that to you on what should happen to that folder, maybe once the docs project is upto date they can be distributed with the dist (the pdf's or html files).

All fine for me to send patch to reviewboard?

**Comment by vega113** [comment]
I think there's no need for review board patch - I ll just merge your pull
request.

**Comment by wisebaldone** [comment]
A new build system/source layout was proposed in 2011. Today it finally got
done.

**Comment by wisebaldone** [comment]
dam sorry, yes ill add those changes

**Comment by wisebaldone** [comment]
Done

**Comment by wisebaldone** [comment]
cant build the source without them.

**Comment by wisebaldone** [comment]
only due to how outdated the sources are, and the conflict with the client. Can be fixed in further patches as i remove the old dependencies, but changing source and build tool i thought would be a bit much for 1 patch

**Comment by wisebaldone** [comment]
done.

**Pull request merged**
